name: 'Submodules Sync'

on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    steps:
    - name: "Update submodules"
      uses: runsascoded/update-submodules@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}